# Generated by Django 5.1.7 on 2025-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_user_bookreview_user_book_author_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='stars_given',
            field=models.IntegerField(),
        ),
    ]
